### ISSUE TITLE
Increase Control Flow

### ISSUE THREAD

**Issue by Khalidbaraka** [NicholasNagy/Parent_Teacher_Web_App#102]
**User Story:** 

As a user, I want to be able to navigate through the webpage with ease, so that I don't have to go back and forth to access different features.

**Description:**

Make sure that every page has access to all the features in the main sidebar of the homepage.

**Sub-tasks:**

#103 : Make sure that you can access the friends, groups, and my account feature from the comments page. 

#104 : Make sure that you can access my account, groups, and friends feature from the friends page.

#105 : Make sure my account button works properly on the create groups page, and on the view group page.

#107 : Make sure on the view profile page that you can access the groups feature, and the friends feature from that page.

#108 : Make a button on every page that allows the user to return to their wall.

**Total Points:** 9

**Acceptance Test:**

All the available pages have access to all the available features or that all the above sub-tasks have their acceptance tests accepted.

**Comment by NicholasNagy** [comment]
Closed with pull request #106
