### ISSUE TITLE
Increase Control Flow in Comments Page

### ISSUE THREAD

**Issue by Khalidbaraka** [NicholasNagy/Parent_Teacher_Web_App#103]
**Increase Control Flow Sub-task** #102 

**User Story:**

As a user, I want to be able to navigate through the webpage with ease, so that I don't have to go back and forth to access different features.

**Description:**

Make sure that you can access the friends, groups, and my account feature from the comments page. Make sure that there are no errors in the process, and that all the information that needs to be sent to the new page, is sent.

**Points:** 2

**Acceptance Test:**

Click on friends, and get sent to friends page.

Click on groups, and get sent to group page.

Click on my account, and get sent to my account page.

**Comment by NicholasNagy** [comment]
Closed with pull request #106
