### ISSUE TITLE
Increase Control Flow in Groups Page

### ISSUE THREAD

**Issue by Khalidbaraka** [NicholasNagy/Parent_Teacher_Web_App#105]
**Increase Control Flow Sub-task** #102 

**User Story:**

As a user, I want to be able to navigate through the webpage with ease, so that I don't have to go back and forth to access different features.

**Description:**

Make sure my account button works properly on the create groups page, and on the view group page. Currently it still uses the old table to view my account, and this is wrong.

**Points:** 1

**Acceptance Test:**

Click on my account in groups page, and be taken to the correct my account page. (Verify information to make sure it is the same as in the correct table in MySQL, and make sure there is no connection with the old table).

**Comment by NicholasNagy** [comment]
Closed with pull request #106
