### ISSUE TITLE
Increase Control Flow in View Profile Page

### ISSUE THREAD

**Issue by Khalidbaraka** [NicholasNagy/Parent_Teacher_Web_App#107]
**Increase Control Flow Sub-task** #102

**User Story:**

As a user, I want to be able to navigate through the webpage with ease, so that I don't have to go back and forth to access different features.

**Description:**

Make sure that the view Profile page can have access to the friends page, and the groups page.

**Points:** 1

**Acceptance Test:**

When you click on friends and groups on the view profile page, it should take you to those particular pages.

**Comment by NicholasNagy** [comment]
Closed with pull request #106
