### ISSUE TITLE
My Wall Button

### ISSUE THREAD

**Issue by Khalidbaraka** [NicholasNagy/Parent_Teacher_Web_App#108]
**Increase Control Flow Sub-task** #102

**User Story:**

As a user, I want to be able to navigate through the webpage with ease, so that I don't have to go back and forth to access different features.

**Description:**

Make a button on every page that allows the user to return to their wall. This includes sending the proper info to the correct post method.

**Sub-tasks:**

* Add button to homepage

* Add button to view account page

* Add button to comment page

* Add button to friends page

* Add button to view groups page

* Add button to edit groups page

**Points:** 3

**Acceptance Test:**

When all the above sub-tasks are completed, and redirect you to your own wall.

**Note:** Although this issue has many sub-tasks, each sub-task is too small to have its own issue, so they will all be held here.

**Comment by NicholasNagy** [comment]
Closed with pull request #106
