### ISSUE TITLE
Messaging friends instead of everyone

### ISSUE THREAD

**Issue by emiletab** [NicholasNagy/Parent_Teacher_Web_App#114]
**User Story:**

As a user, I want to be able to message my friends, not necessarily everyone.

**Description:**

Rearrange messaging so that you can message friends. So create a button on the friends page that sends the required info to the file that deals with messaging, so that you can message your individual friends.

**Points:** 3

**Acceptance Test:**

Login, click on friends, then click on the button to message your friend. Log in as friend in new window, click on friends, and click message on the original logged in friend. Start a conversation, then log back out, and then back in again to make sure you conversation was registered properly.

**Comment by NicholasNagy** [comment]
Closed with pull request #113
