### ISSUE TITLE
Allow groups’ admins to accept/reject new members to groups

### ISSUE THREAD

**Issue by makchamp** [NicholasNagy/Parent_Teacher_Web_App#117]
User Story:

As a user, I want group admins/leaders (those who created the group) to accept or reject new members to their groups. 

Sub-Tasks:

1. Users can view other users' groups (1 point). #128 
2. Users can send requests to the group leader (either requesting themselves to join or requesting another user to join the group) (2 points) #134 
3. Group leader can view and respond to requests (either by accepting or rejecting them). Accepting would add the user to the group. (1 point).  #134 

Points: 6

**Comment by NicholasNagy** [comment]
This issue was closed with pull request #136
