### ISSUE TITLE
Learning pushnotifications module for Implementing notifications 

### ISSUE THREAD

**Issue by emiletab** [NicholasNagy/Parent_Teacher_Web_App#118]
**Implementing Notifications sub-task: #101**
**User Story:**
As a user, I want to be able to receive notifications when other posts on my wall or send me a private message.

**Description:**
I need to learn more about pushnotifications module that can help me implement the feature correctly.

**Points: 1**

**Acceptance Test:**
Being able to fully understand the documentation of the module.

**Comment by NicholasNagy** [comment]
Closed with pull request #127

**Comment by NicholasNagy** [comment]
Due to the nature of this issue, it is not relevant and hence will be removed
