### ISSUE TITLE
Use nodemailer to send an email 

### ISSUE THREAD

**Issue by Khalidbaraka** [NicholasNagy/Parent_Teacher_Web_App#122]
This is a sub-task of issue #121 

User Story: 
As a user, I should be able to receive my password when I forgot it via email so that I can access my account. 

Description of task:
Once the user submits their e-mail, retrieve the user's password from the database using this email, then using nodemailer send an email to the user giving them their password, which they can then use to log back into their account and change their password if they wish.

Points: 4

**Comment by Khalidbaraka** [comment]
![Uploading Screen Shot 2018-11-07 at 8.06.26 PM.png…]()

**Comment by Khalidbaraka** [comment]
<img width="480" alt="screen shot 2018-11-07 at 8 06 26 pm" src="https://user-images.githubusercontent.com/25536115/48179446-3dfe4280-e2ed-11e8-8d08-94e990b00745.png">

**Comment by NicholasNagy** [comment]
Due to the nature of this issue, it is no longer relevant and will be closed

**Comment by NicholasNagy** [comment]
closed with pull request #133
