### ISSUE TITLE
Handle Forgot Password Exceptions

### ISSUE THREAD

**Issue by Khalidbaraka** [NicholasNagy/Parent_Teacher_Web_App#123]
This is a sub-task of issue #121 

User Story:
As a user, I should be able to receive my password when I forgot it via email so that I can access my account.

Description:
Handle the special case that when an e-mail does not exist in our database, the page is redirected to another page to explain this error to the user.

Points:2

**Comment by Khalidbaraka** [comment]
[design.pdf](https://github.com/NicholasNagy/Parent_Teacher_Web_App/files/2560430/design.pdf)

**Comment by NicholasNagy** [comment]
Closed with pull request #157
