### ISSUE TITLE
Implement test cases for new features

### ISSUE THREAD

**Issue by makchamp** [NicholasNagy/Parent_Teacher_Web_App#138]
Implement test cases for each new feature being implemented. 

1. Joining groups and group access rights depending on user status (admin, member or non member) (1 point)
2. Forgot password (1 point)
3. Notifications for wall posts and messaging (1 point) 
4. User search in friends and groups (1 point)
5. Image posting on walls (1 point)

Points: 5

**Comment by NicholasNagy** [comment]
Closed with pull request #159
