### ISSUE TITLE
Tagging friends

### ISSUE THREAD

**Issue by NicholasNagy** [NicholasNagy/Parent_Teacher_Web_App#148]
User Story:

As a user, I want to be able to tag friends so that I can show them posts that I enjoy.

Description:

Find some way to use "@" followed by the name of someone to tag them. 

Sub-tasks:

* Dynamically generate a table of friends when the user is typing and if he clicks on one, autocomplete the name (8 points)

* Send a notification once the user has posted to the tagged individual leading them to the contents of the post (2 points)

* Port code to comments so that people can tag in comments. (5 points)

Total points: 15

Note: Priority for complete the above tasks is in the order that they are written

**Comment by emiletab** [comment]
This issue was closed with pull request #149
