### ISSUE TITLE
Handing infinite likes and dislikes

### ISSUE THREAD

**Issue by Khalidbaraka** [NicholasNagy/Parent_Teacher_Web_App#152]
User Story:

As a user, I want to be able like or dislike on a specific post in case I like/dislike the contents of that post.

Description:
1-Allowing the user to like or dislike a post however, the user can not have multiple likes or dislikes on a specific post. 
2-The user can not have multiple likes or dislikes on a specific post.However, the user should be able to change the like to dislike which will result in: 

-  decrement the total likes in the post

-  increment the total dislikes in the post

- update the value of likes to zero 

the same thing goes to the other way around.

Sub-tasks:
create a database table (2 points) #153 

Total points: 2

**Comment by emiletab** [comment]
this was done  in #157
