### ISSUE TITLE
create a database table 

### ISSUE THREAD

**Issue by Khalidbaraka** [NicholasNagy/Parent_Teacher_Web_App#153]
#152 
User Story:
As a user, I want to be able like or dislike on a specific post in case I like/dislike the contents of that post.

Description:
The significance of creating a database table related to likes is that we need to clarify if the user has already liked or disliked the post and based on that we can handle the process and to keep track of what post has the user liked or disliked.

Total points: 2

**Comment by emiletab** [comment]
This was closed in #157
