### ISSUE TITLE
Improve styling and overall page presentation

### ISSUE THREAD

**Issue by makchamp** [NicholasNagy/Parent_Teacher_Web_App#154]
**Story**

As a user I want to view and interact with a responsive and intuitive web page. All page content must be easy to find and well organized. 

**Description:**

Fix bugs and improve issues related to clipping, overlapping of content, color, theme and size choice, page scaling and layout organization.   
Main page to improve on is the wall page. 

**Points: 6**

**Comment by NicholasNagy** [comment]
Closed with pull request #155
