### ISSUE TITLE
Capability to add friends and go to friend's walls

### ISSUE THREAD

**Issue by NicholasNagy** [NicholasNagy/Parent_Teacher_Web_App#72]
**User Story:**

As a user, I want to be able to post to other people's walls.

**Description:**

Add functionality to add friends using emails. Add functionality to see all of friends, with links, so that you can access friends' walls when you click on it.

Prerequisite: Issue #71 

Points: 5

**Comment by makchamp** [comment]
closed with pull request #97 and #82
