### ISSUE TITLE
Write and Implement 3 test cases

### ISSUE THREAD

**Issue by NicholasNagy** [NicholasNagy/Parent_Teacher_Web_App#75]
**Description:**

To facilitate continuous integration, come up with 3 test cases, and write test code to add to your continuous integration network.

Test case 1: Automate signup and validate with a login, and assert that the obtained user is the one we want. Points: 3

Test case 2: Automate looking through the entire list of users to make sure there are no duplicates, and handling them if there are. Points: 3

Test case 3: Validate that the correct info is retrieved when viewing user profile
Points: 1

Test case 4: Automate editing of user info, and making sure the changes were made
Points: 1

Points: 8

**Comment by emiletab** [comment]
Concluded with pull request #91
