### ISSUE TITLE
Refactoring code

### ISSUE THREAD

**Issue by NicholasNagy** [NicholasNagy/Parent_Teacher_Web_App#98]
**User Story:**

As someone who is looking at this GitHub repository, I want to see organized code, so that I can better understand what is going on in the code.

**Description:**

Clean up the code to make it more organized, and remove all the files that no longer have a use in our code. Organize the code that loads wall posts, so that if ever we want to change anything related to posts, we will only need to change it in one file.

**Sub-tasks:**

1. Refactor server to use new functions. Clean up code. Create functions for redundant code, particularly in the files that load the wall.

2. Delete useless files/ cleanup repository. (Make a list and delete that list)

Points: 3

**Acceptance Test:**

Make sure that all the following are still occurring, and not crashing the server:

* log in works fine

* sign up works fine

* posting still works fine (including liking and disliking)

* viewing comment page works fine (including commenting on this page)

* groups works fine (including creation of groups and searching and adding people)

* friends works fine (including adding friends and searching for them)

* viewing and editing the profile still works

**Comment by Khalidbaraka** [comment]
I'm going to finish up what you started

**Comment by NicholasNagy** [comment]
Sub-task 1 was completed with pull request #106

**Comment by Khalidbaraka** [comment]
Closed with pull request #106 and #116
